// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // await Firebase.initializeApp(
  // options: FirebaseOptions(
  // apiKey: 'AIzaSyD-s-UxLopF1HMn-j4KPWSaM0aJJnYWNs8',
  // appId: '1:142114978940:android:ec733baa123ef0fc275df9',
  // messagingSenderId: '142114978940',
  // projectId: 'push-notification-with-f-8b80a',
  // storageBucket: 'push-notification-with-f-8b80a.appspot.com',
  // ),
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGG4Watl0m7TND4rfJmfqKqhzBlgYMoME',
    appId: '1:921063598468:android:1c14d7dbbc3b8d12b5d5d1',
    messagingSenderId: '921063598468',
    projectId: 'fcm-for-second',
    storageBucket: 'fcm-for-second.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGG4Watl0m7TND4rfJmfqKqhzBlgYMoME',
    appId: '1:921063598468:android:1c14d7dbbc3b8d12b5d5d1',
    messagingSenderId: '921063598468',
    projectId: 'fcm-for-second',
    storageBucket: 'fcm-for-second.appspot.com',
    iosClientId: '757941782079-mtmoukdf91egsh8tbjrfgj577pl25jam.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotifications',
  );
}
